### ISSUE TITLE
About WFLW pre-processing

### ISSUE THREAD

**Issue by polo5** [starhiking/HeatmapInHeatmap#4]
Hi! Thanks again for this work:)

I've been benchmarking a few things and noticed that there is a difference between recent repos (HIH, SLPT, ..)  depending on how WFLW is processed. You mention that `We have processed the dataset following PFLD` but I can't find any description of what that processing involves in their paper.

In my experiments your dataset gives a better performance (by ~0.2) than say the SPLT dataset pipeline, even when all augmentations are removed on both. They seem to use keypoints to find bboxes but I suspect you used the provided bboxes directly/ If I visualize the images produced by the 2 datasets they look very similar. 

Any idea why this could be the case? Is there possibly more alignment in your dataset making things a bit easier?

Thanks!

**Comment by starhiking** [comment]
Hi! Thanks for your attention.

The original WFLW [annoations](https://wywu.github.io/projects/LAB/WFLW.html) have provided the coordinates of the upper left corner and lower right corner of the detection rectangle. You can calculate the max and min coordinates among the 100 points (98 + 2) to get the bounding box. The effect with the upper left and lower right corners to re-get the rectangle will be better. Also, you can use an accurate face detector to re-calculate the face box, which may improve performance in application.
